import {useEffect,useState} from 'react';
import './garage.css';
type Day={date:string;counts:Record<string,number>};
type BoardEntry={id:string;name:string;elapsed:number};
type Stats={daily:Day[];startedAt:string|null;updatedAt:string;board:BoardEntry[]};
const analyticsUrl='https://vercel.com/bryce-rambachs-projects/brycerambach-portfolio/analytics';
const stages=[['visit','Opened the site'],['car_entered','Got in the Porsche'],['tahoe_reached','Made it to Tahoe'],['race_started','Started the race'],['race_finished','Crossed the line'],['time_posted','Posted a time']];
const lap=(ms:number)=>(ms/1000).toFixed(3)+'s';
export default function Garage(){
  const [stats,setStats]=useState<Stats|null>(null),[locked,setLocked]=useState(false),[busy,setBusy]=useState(true),[error,setError]=useState(''),[days,setDays]=useState(7);
  async function load(){
    setBusy(true);setError('');
    try{const response=await fetch('/api/admin');if(response.status===401){setStats(null);setLocked(true);return;}const data=await response.json();if(!response.ok)throw new Error(data.error);setStats(data);setLocked(false);}catch(e){setError(e instanceof Error?e.message:'Couldn’t open the logbook.');}finally{setBusy(false);}
  }
  useEffect(()=>{document.title='Garage office | Bryce Rambach';void load();},[]);
  async function login(event:React.FormEvent<HTMLFormElement>){
    event.preventDefault();const form=event.currentTarget;const password=String(new FormData(form).get('password')??'');setBusy(true);setError('');
    try{const response=await fetch('/api/admin',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'login',password})});const data=await response.json();form.reset();if(!response.ok)throw new Error(data.error);await load();}catch(e){setError(e instanceof Error?e.message:'Couldn’t unlock the garage.');}finally{setBusy(false);}
  }
  async function logout(){setBusy(true);try{const response=await fetch('/api/admin',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'logout'})});if(!response.ok)throw new Error();setStats(null);setLocked(true);}catch{setError('Couldn’t lock the garage. Try again.');}finally{setBusy(false);}}
  const selected=stats?.daily.slice(-days)??[];
  const count=(key:string)=>selected.reduce((sum,day)=>sum+(day.counts[key]??0),0);
  const visits=count('visit'),races=count('race_started'),finishes=count('race_finished');
  const max=Math.max(1,...selected.map(day=>day.counts.visit??0));
  const bryceRank=stats?.board.findIndex(row=>row.name.toLowerCase().startsWith('bryce'))??-1;
  return <main className="garage"><div className="garage-shell"><header className="garage-mast"><a href="/" aria-label="Back to the road" className="garage-brand">b<span>THE LONG WAY<br/>PRIVATE GARAGE</span></a><span className="garage-owner">BRYCE RAMBACH / OWNER’S COPY</span>{stats&&<button onClick={logout} disabled={busy}>Lock up ↗</button>}</header>
    <div className="garage-heading"><div><span className="garage-kicker">AFTER THE DRIVE</span><h1>The garage office.</h1><p>A little paperwork for a very unnecessary Porsche.</p></div><div className="garage-stamp">EST. 2026<br/><span>TAKE THE<br/>LONG WAY</span></div></div>
    {error&&<p role="alert" className="garage-error">{error}</p>}
    {locked?<section className="garage-login"><span className="garage-kicker">OWNER ACCESS / 01</span><h2>Keys, please.</h2><p>Your logbook stays in here.</p><form onSubmit={login}><label htmlFor="garage-password">Garage password</label><input id="garage-password" name="password" type="password" autoComplete="current-password" maxLength={128} required/><button disabled={busy}>{busy?'Unlocking…':'Unlock the office ↗'}</button></form><small>No public sign-up. Just you and the numbers.</small></section>:!stats?<div className="garage-login"><p role="status">{busy?'Opening the logbook…':'The logbook is unavailable.'}</p>{!busy&&<button onClick={load}>Try again</button>}</div>:<>
      <div className="garage-toolbar"><div role="group" aria-label="Reporting period">{[[1,'Today'],[7,'7 days'],[30,'30 days']].map(([value,label])=><button key={value} aria-pressed={days===value} onClick={()=>setDays(Number(value))}>{label}</button>)}</div><span>UTC DAYS / {new Date(stats.updatedAt).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'})}</span><button disabled={busy} onClick={load}>{busy?'Checking…':'Refresh ↻'}</button></div>
      <section className="garage-dials" aria-label="Journey totals">{[['Site sessions',visits,'Tracked browser-tab sessions'],['Race starts',races,'Sessions that reached the green light'],['Race finishes',finishes,'Sessions that crossed the finish line']].map(([label,value,note],i)=><article className="garage-dial" key={label}><span className="garage-kicker">0{i+1} / {label}</span><div className="garage-gauge"><strong>{value}</strong></div><p>{note}</p></article>)}</section>
      <div className="garage-grid"><section className="garage-paper"><div className="garage-section-title"><span className="garage-kicker">01 / THE ROUTE</span><span>{days===1?'TODAY':`LAST ${days} DAYS`}</span></div><h2>How far did they go?</h2><p className="garage-muted">One count per step, per browser-tab session.</p><ol className="garage-stages">{stages.map(([key,label],i)=><li key={key}><span className="garage-step-number">0{i+1}</span><div><span>{label}</span><div className="garage-track"><i style={{width:`${Math.min(100,count(key)/Math.max(1,visits)*100)}%`}}/></div></div><strong>{count(key)}</strong></li>)}</ol><p className="garage-footnote">Steps count on the day they happen. Sessions can span days, so this is a progress tally, not a matched visitor funnel.</p></section>
      <section className="garage-paper"><div className="garage-section-title"><span className="garage-kicker">02 / TRAFFIC LOG</span><span>{visits} SESSIONS</span></div><h2>A little coming and going.</h2><div className="garage-bars" role="img" aria-label={selected.map(day=>`${day.date}: ${day.counts.visit??0} sessions`).join('; ')}>{selected.map(day=><div key={day.date} title={`${day.date}: ${day.counts.visit??0}`}><i style={{height:`${(day.counts.visit??0)/max*100}%`}}/><span>{day.date.slice(8)}</span></div>)}</div>{visits===0&&<p className="garage-muted">The logbook’s open. Waiting for the first session.</p>}<div className="garage-sources">{[['direct','Direct / internal'],['x','X'],['linkedin','LinkedIn'],['github','GitHub'],['other','Other sites']].map(([key,label])=><div key={key}><span>{label}</span><strong>{count('source:'+key)}</strong></div>)}</div><a className="garage-vercel" href={analyticsUrl} target="_blank" rel="noreferrer">Visitor estimates & page views in Vercel ↗</a><p className="garage-footnote">These are session counts from our own logbook. Vercel’s visitor estimates use a different method.</p></section>
      <section className="garage-paper garage-races"><div className="garage-section-title"><span className="garage-kicker">03 / TIMING DESK</span><span>ALL-TIME BOARD</span></div><div className="garage-race-heading"><div><h2>Who’s been quick?</h2><p className="garage-muted">{bryceRank>=0?`You’re sitting at #${bryceRank+1}. ${bryceRank===0?'Enjoy the view.':'There’s a reason to take another lap.'}`:'Your next lap belongs here.'}</p></div><span className="garage-lap-count">{stats.board.length}<small>POSTED TIMES</small></span></div><table><thead><tr><th>Place</th><th>Driver</th><th>Time</th><th>Behind first</th></tr></thead><tbody>{stats.board.slice(0,20).map((row,i)=><tr key={row.id} className={row.name.toLowerCase().startsWith('bryce')?'garage-your-lap':''}><td>{String(i+1).padStart(2,'0')}</td><td>{row.name}</td><td>{lap(row.elapsed)}</td><td>{i?'+'+lap(row.elapsed-stats.board[0].elapsed):'FASTEST'}</td></tr>)}</tbody></table>{!stats.board.length&&<p>No times posted yet.</p>}<p className="garage-footnote">The board retains up to 200 times and shows the fastest 20 here. The AI exhibition lap uses direct road knowledge.</p></section></div>
      <footer className="garage-footer"><span>LOGBOOK OPENED {stats.startedAt?new Date(stats.startedAt).toLocaleDateString('en-US',{month:'short',day:'numeric',year:'numeric'}):'WHEN THE FIRST SESSION ARRIVES'}</span><span>Numbers since tracking began. No history invented.</span></footer>
    </>}
  </div></main>;
}
