import { useState } from 'react';
import { InspectImage } from './InspectImage';
const stages=['Mapping','Testing','Live'];
const perspectives=[{name:'The specialist',file:'today',heading:'What needs a person?',text:'A ranked list turns operational state into a sentence and an action.'},{name:'The client',file:'hub',heading:'Whose move is it?',text:'The hub makes the next decision and the handover visible.'},{name:'Ongoing support',file:'monitoring',heading:'What happened, and what’s next?',text:'An incident needs context: the affected process, the owner and the next action.'}];
export default function PortalStudy(){const [stage,setStage]=useState(0);const [mapped,setMapped]=useState(false);const [tested,setTested]=useState(false);const [perspective,setPerspective]=useState(0);const frame=perspectives[perspective];
  const reset=()=>{setStage(0);setMapped(false);setTested(false);};
  return <article className="ps-portal"><header className="ps-portal__hero"><span className="ps-eyebrow">Integration portal / Anonymised employee work</span><h1 tabIndex={-1}>The work.<br/><em>In order.</em></h1><div><p>A clear path through<br/>a complicated delivery.</p><span>Interface design & frontend engineering<br/>HR and payroll integrations</span></div><div className="ps-portal__hero-path" aria-hidden="true">Connect <i/> Configure <i/> Review <i/> Deliver</div></header>
    <section className="ps-portal__journey"><header><div><span className="ps-eyebrow">Follow a fictional integration</span><h2>One record.<br/>A shared next step.</h2></div><p>See how a client decision becomes a review, then a clear handover. This is a simplified portfolio demonstration.</p></header><div className="ps-portal__workspace"><aside><span className="ps-eyebrow">Halden Logistics</span><h3>HR → Payroll</h3><ol>{stages.map((name,index)=><li key={name} className={stage===index?'is-active':stage>index?'is-done':''}><span>{stage>index?'✓':`0${index+1}`}</span>{name}</li>)}</ol><small>Fictional data<br/>No external actions</small></aside><div className="ps-portal__task" aria-live="polite"><span className="ps-eyebrow">{stage===0?'Client review':stage===1?'Delivery review':'Handover complete'}</span><h3>{stage===0?'One mapping needs your eye.':stage===1?'Check the agreed behaviour.':'Ready for everyday work.'}</h3>{stage===0?<><p>Confirm how this department should appear in payroll.</p><p className="ps-sample-note">Employer-owned work. All screens are redrawn with a fictional cast.</p><div className="ps-portal__mapping"><span>People & Culture<small>HR department</small></span><i>→</i><span>Human Resources<small>Payroll department</small></span></div><label><input type="checkbox" checked={mapped} onChange={event=>setMapped(event.target.checked)}/> This mapping matches the intended department.</label><button disabled={!mapped} onClick={()=>setStage(1)}>Confirm sample mapping →</button></>:stage===1?<><p>The review keeps the agreed mapping beside the sample result.</p><div className="ps-portal__check"><span>✓</span><div>Department mapping<small>People & Culture → Human Resources</small></div><b>Sample match</b></div><label><input type="checkbox" checked={tested} onChange={event=>setTested(event.target.checked)}/> I’ve reviewed this illustrative result.</label><button disabled={!tested} onClick={()=>setStage(2)}>Complete sample review →</button></>:<><p>The completed review stays with the integration. Ongoing monitoring becomes the next place to look.</p><div className="ps-portal__complete"><span>✓</span><div>Mapping confirmed<br/>Review recorded<small>Sample journey complete. Nothing was deployed.</small></div></div><button onClick={reset}>Replay the journey ↺</button></>}</div></div></section>
    <section className="ps-portal__perspectives"><header><span className="ps-eyebrow">The interface, in context</span><h2>Same work.<br/><em>Different needs.</em></h2></header><nav aria-label="Portal perspectives">{perspectives.map((item,index)=><button key={item.name} aria-pressed={perspective===index} onClick={()=>setPerspective(index)}>{item.name}</button>)}</nav><div className={`ps-portal__frame ps-portal__frame--${frame.file}`}><img src={`/projects/portal/${frame.file}.png`} alt={`Fictional redrawn portal screen: ${frame.name.toLowerCase()}`} loading="lazy"/></div><div className="ps-portal__caption"><h3>{frame.heading}</h3><p>{frame.text}</p><InspectImage src={`/projects/portal/${frame.file}.png`} alt={`Anonymised portal: ${frame.name.toLowerCase()}`}/></div></section>
    <section className="ps-editorial"><span className="ps-eyebrow">The product decision</span><h2>Let people follow<br/>the work.</h2><p>Configuration is only one part of delivery. The interface also needs to say what’s waiting, who owns the next step and what a completed review means.</p><div className="ps-editorial__pair"><div><span className="ps-eyebrow">Design</span><h3>Different views, one record.</h3><p>A specialist needs to find the next intervention. A client needs to understand their next decision. The information architecture gives both a view of the same integration.</p></div><div><span className="ps-eyebrow">Engineering</span><h3>Carry decisions through delivery.</h3><p>The project spans two portal generations, with configuration, mapping, testing and support interfaces. This study presents their interaction model through fictional examples.</p></div></div></section>
    <footer className="ps-study-footer"><div>Interface design & frontend engineering<br/>Bryce Rambach, as an employee</div><p>Employer-owned work. The company, vendors and people are unnamed. All screens are redrawn with a fictional cast. The demonstration doesn’t connect to production or establish current operational results.</p></footer>
  </article>;
}
